# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Per_a_proc2.py
# Created on: 2019-04-12 11:09:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------
# Import arcpy module
import arcpy

#Set Workspace
arcpy.env.workspace = r"C:\Caio\Curva_Permanencia\\Vazao.gdb\\"

##Check Extentions
arcpy.CheckOutExtension("GeoStats")

#Set overwrite
arcpy.env.overwriteOutput = True


print ("Programa que estabelece média de Vazão das UHE por perídos determinados através da interpolação IDW da estação mais próxima a UHE em período de tempo determinado")


# Local variables:
Est_Curva = "Database Connections\\binewdev@stagedw@usrconsultas.sde\\StageDW.SFG.StgEstacaoCurvaPermanencia"
Est_BI = "Est_BI"
Est_Join = Est_BI
Estacao_Vazia = r"C:\Caio\Curva_Permanencia\Vazao.gdb\Estacao_Vazia"
EstAproces = "Est_proces"
Per_a_proc = "C:\\Caio\\Curva_Permanencia\\Vazao.gdb\\Per_a_proc"
Per_fc = 'Per_fc'
WsPeriodo = r"C:\Caio\Curva_Permanencia\\Vazao.gdb\\"
Aprov_Bd = "C:\\Caio\\Curva_Permanencia\\Shapefiles\\APROVEITAMENTOS.shp"
Aprov_Op = r"C:\Caio\Curva_Permanencia\\Aproveitamentos\\Aprov.shp"


# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(Est_Curva, "MdaLongitude", "MdaLatitude", Est_BI, "GEOGCS['GCS_SIRGAS_2000',DATUM['D_SIRGAS_2000',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8,98315284119521E-09;0,001;0,001;IsHighPrecision", "")

# Process: Make XY Event Layer (2)
arcpy.MakeXYEventLayer_management(Estacao_Vazia, "MdaLongitude", "MdaLatitude", EstAproces, "GEOGCS['GCS_SIRGAS_2000',DATUM['D_SIRGAS_2000',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8,98315284119521E-09;0,001;0,001;IsHighPrecision", "")

# Process: Add Join
arcpy.AddJoin_management(Est_BI, "IdeRegistroPeriodo", EstAproces, "IdeRegistroPeriodo", "KEEP_ALL")

#print ListFields
field_names = [f.name for f in arcpy.ListFields(Est_Join)]
print field_names

# Process: Table Select
arcpy.TableSelect_analysis(Est_Join, Per_a_proc, 'Estacao_Vazia_Features.DthInicioPeriodo IS NULL AND StageDW.SFG.StgEstacaoCurvaPermanencia_Features.MdaLatitude IS NOT NULL')


#Make XY Layer de período a processar

arcpy.MakeXYEventLayer_management(Per_a_proc, "StageDW_SFG_StgEstacaoCurvaPermanencia_Features_MdaLongitude", "StageDW_SFG_StgEstacaoCurvaPermanencia_Features_MdaLatitude", Per_fc, "GEOGCS['GCS_SIRGAS_2000',DATUM['D_SIRGAS_2000',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8,98315284119521E-09;0,001;0,001;IsHighPrecision", "")


#Split by attributes

arcpy.SplitByAttributes_analysis(Per_fc,WsPeriodo, "StageDW_SFG_StgEstacaoCurvaPermanencia_Features_DthInicioPeriodo;StageDW_SFG_StgEstacaoCurvaPermanencia_Features_DthFimPeriodo")


#Lista de FeatureClass de Pontos a processar
FcPontos = arcpy.ListFeatureClasses('','Point')


#Iteracao do IDW com extent do Brasil
for fc in FcPontos:
    OutIDW = arcpy.Describe(fc).baseName + "_IDW"
    #arcpy.IDW_ga(in_features=fc, z_field="Estacao_BI_Features_MdaiDRE_LT", out_ga_layer="", out_raster=OutIDW,
     #            cell_size="0,156020628", power="2",
      #           search_neighborhood="NBRTYPE=Smooth S_MAJOR=11,7367757908039 S_MINOR=11,7367757908039 ANGLE=0 SMOOTH_FACTOR=0,4",
       #          weight_field="")
    tempEnvironment0 = arcpy.env.newPrecision
    arcpy.env.newPrecision = "SINGLE"
    tempEnvironment1 = arcpy.env.autoCommit
    arcpy.env.autoCommit = "1000"
    tempEnvironment2 = arcpy.env.XYResolution
    arcpy.env.XYResolution = ""
    tempEnvironment3 = arcpy.env.processingServerUser
    arcpy.env.processingServerUser = ""
    tempEnvironment4 = arcpy.env.XYDomain
    arcpy.env.XYDomain = ""
    tempEnvironment5 = arcpy.env.processingServerPassword
    arcpy.env.processingServerPassword = ""
    tempEnvironment6 = arcpy.env.scratchWorkspace
    arcpy.env.scratchWorkspace = "C:\\caio\\Curva_Permanencia\\Vazao.gdb"
    tempEnvironment7 = arcpy.env.cartographicPartitions
    arcpy.env.cartographicPartitions = ""
    tempEnvironment8 = arcpy.env.terrainMemoryUsage
    arcpy.env.terrainMemoryUsage = "false"
    tempEnvironment9 = arcpy.env.MTolerance
    arcpy.env.MTolerance = ""
    tempEnvironment10 = arcpy.env.compression
    arcpy.env.compression = "LZ77"
    tempEnvironment11 = arcpy.env.coincidentPoints
    arcpy.env.coincidentPoints = "MEAN"
    tempEnvironment12 = arcpy.env.randomGenerator
    arcpy.env.randomGenerator = "0 ACM599"
    tempEnvironment13 = arcpy.env.outputCoordinateSystem
    arcpy.env.outputCoordinateSystem = "GEOGCS['GCS_SIRGAS_2000',DATUM['D_SIRGAS_2000',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]"
    tempEnvironment14 = arcpy.env.rasterStatistics
    arcpy.env.rasterStatistics = "STATISTICS 1 1"
    tempEnvironment15 = arcpy.env.ZDomain
    arcpy.env.ZDomain = ""
    tempEnvironment16 = arcpy.env.transferDomains
    arcpy.env.transferDomains = "false"
    tempEnvironment17 = arcpy.env.maintainAttachments
    arcpy.env.maintainAttachments = "true"
    tempEnvironment18 = arcpy.env.resamplingMethod
    arcpy.env.resamplingMethod = "NEAREST"
    tempEnvironment19 = arcpy.env.snapRaster
    arcpy.env.snapRaster = ""
    tempEnvironment20 = arcpy.env.projectCompare
    arcpy.env.projectCompare = "NONE"
    tempEnvironment21 = arcpy.env.cartographicCoordinateSystem
    arcpy.env.cartographicCoordinateSystem = "GEOGCS['GCS_SIRGAS_2000',DATUM['D_SIRGAS_2000',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]"
    tempEnvironment22 = arcpy.env.configKeyword
    arcpy.env.configKeyword = ""
    tempEnvironment23 = arcpy.env.outputZFlag
    arcpy.env.outputZFlag = "Same As Input"
    tempEnvironment24 = arcpy.env.qualifiedFieldNames
    arcpy.env.qualifiedFieldNames = "true"
    tempEnvironment25 = arcpy.env.tileSize
    arcpy.env.tileSize = "128 128"
    tempEnvironment26 = arcpy.env.parallelProcessingFactor
    arcpy.env.parallelProcessingFactor = ""
    tempEnvironment27 = arcpy.env.pyramid
    arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
    tempEnvironment28 = arcpy.env.referenceScale
    arcpy.env.referenceScale = ""
    tempEnvironment29 = arcpy.env.processingServer
    arcpy.env.processingServer = ""
    tempEnvironment30 = arcpy.env.extent
    arcpy.env.extent = "-73,980047 -33,754354 -34,822856 5,250803"
    tempEnvironment31 = arcpy.env.XYTolerance
    arcpy.env.XYTolerance = ""
    tempEnvironment32 = arcpy.env.tinSaveVersion
    arcpy.env.tinSaveVersion = "CURRENT"
    tempEnvironment33 = arcpy.env.nodata
    arcpy.env.nodata = "NONE"
    tempEnvironment34 = arcpy.env.MDomain
    arcpy.env.MDomain = ""
    tempEnvironment35 = arcpy.env.spatialGrid1
    arcpy.env.spatialGrid1 = "0"
    tempEnvironment36 = arcpy.env.cellSize
    arcpy.env.cellSize = "MAXOF"
    tempEnvironment37 = arcpy.env.outputZValue
    arcpy.env.outputZValue = ""
    tempEnvironment38 = arcpy.env.outputMFlag
    arcpy.env.outputMFlag = "Same As Input"
    tempEnvironment39 = arcpy.env.geographicTransformations
    arcpy.env.geographicTransformations = "NAD_1927_To_NAD_1983_NADCON"
    tempEnvironment40 = arcpy.env.spatialGrid2
    arcpy.env.spatialGrid2 = "0"
    tempEnvironment41 = arcpy.env.ZResolution
    arcpy.env.ZResolution = ""
    tempEnvironment42 = arcpy.env.mask
    arcpy.env.mask = ""
    tempEnvironment43 = arcpy.env.spatialGrid3
    arcpy.env.spatialGrid3 = "0"
    tempEnvironment44 = arcpy.env.maintainSpatialIndex
    arcpy.env.maintainSpatialIndex = "false"
    tempEnvironment45 = arcpy.env.workspace
    arcpy.env.workspace = "C:\\caio\\Curva_Permanencia\\Vazao.gdb"
    tempEnvironment46 = arcpy.env.MResolution
    arcpy.env.MResolution = ""
    tempEnvironment47 = arcpy.env.derivedPrecision
    arcpy.env.derivedPrecision = "HIGHEST"
    tempEnvironment48 = arcpy.env.ZTolerance
    arcpy.env.ZTolerance = ""
    arcpy.IDW_ga(fc, "StageDW_SFG_StgEstacaoCurvaPermanencia_Features_MdaiDRE_LT", "", OutIDW, "0,156020628", "2", "NBRTYPE=Smooth S_MAJOR=11,7367757908039 S_MINOR=11,7367757908039 ANGLE=0 SMOOTH_FACTOR=0,4", "")
    arcpy.env.newPrecision = tempEnvironment0
    arcpy.env.autoCommit = tempEnvironment1
    arcpy.env.XYResolution = tempEnvironment2
    arcpy.env.processingServerUser = tempEnvironment3
    arcpy.env.XYDomain = tempEnvironment4
    arcpy.env.processingServerPassword = tempEnvironment5
    arcpy.env.scratchWorkspace = tempEnvironment6
    arcpy.env.cartographicPartitions = tempEnvironment7
    arcpy.env.terrainMemoryUsage = tempEnvironment8
    arcpy.env.MTolerance = tempEnvironment9
    arcpy.env.compression = tempEnvironment10
    arcpy.env.coincidentPoints = tempEnvironment11
    arcpy.env.randomGenerator = tempEnvironment12
    arcpy.env.outputCoordinateSystem = tempEnvironment13
    arcpy.env.rasterStatistics = tempEnvironment14
    arcpy.env.ZDomain = tempEnvironment15
    arcpy.env.transferDomains = tempEnvironment16
    arcpy.env.maintainAttachments = tempEnvironment17
    arcpy.env.resamplingMethod = tempEnvironment18
    arcpy.env.snapRaster = tempEnvironment19
    arcpy.env.projectCompare = tempEnvironment20
    arcpy.env.cartographicCoordinateSystem = tempEnvironment21
    arcpy.env.configKeyword = tempEnvironment22
    arcpy.env.outputZFlag = tempEnvironment23
    arcpy.env.qualifiedFieldNames = tempEnvironment24
    arcpy.env.tileSize = tempEnvironment25
    arcpy.env.parallelProcessingFactor = tempEnvironment26
    arcpy.env.pyramid = tempEnvironment27
    arcpy.env.referenceScale = tempEnvironment28
    arcpy.env.processingServer = tempEnvironment29
    arcpy.env.extent = tempEnvironment30
    arcpy.env.XYTolerance = tempEnvironment31
    arcpy.env.tinSaveVersion = tempEnvironment32
    arcpy.env.nodata = tempEnvironment33
    arcpy.env.MDomain = tempEnvironment34
    arcpy.env.spatialGrid1 = tempEnvironment35
    arcpy.env.cellSize = tempEnvironment36
    arcpy.env.outputZValue = tempEnvironment37
    arcpy.env.outputMFlag = tempEnvironment38
    arcpy.env.geographicTransformations = tempEnvironment39
    arcpy.env.spatialGrid2 = tempEnvironment40
    arcpy.env.ZResolution = tempEnvironment41
    arcpy.env.mask = tempEnvironment42
    arcpy.env.spatialGrid3 = tempEnvironment43
    arcpy.env.maintainSpatialIndex = tempEnvironment44
    arcpy.env.workspace = tempEnvironment45
    arcpy.env.MResolution = tempEnvironment46
    arcpy.env.derivedPrecision = tempEnvironment47
    arcpy.env.ZTolerance = tempEnvironment48

#Listar Rasters no GDB

ListIDW = arcpy.ListRasters()


#Select dos Aproveitamentos

arcpy.Select_analysis(Aprov_Bd, Aprov_Op, "ESTAGIO = 3 AND TIPO IN (1,5)")


#Extrair valores do IDW para os pontos de Aproveitamento

#for List in ListIDW

